name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Select Xcode
        run: |
          if [ -d /Applications/Xcode_26.3.0.app ]; then
            sudo xcode-select -s /Applications/Xcode_26.3.0.app
          elif [ -d /Applications/Xcode.app ]; then
            sudo xcode-select -s /Applications/Xcode.app
          fi
          xcodebuild -version

      - name: Compile Autoloader
        run: |
          agvtool new-version -all $(git rev-parse --short HEAD)
          make iphoneos
          mkdir upload
          mv packages/* upload/

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" _build/Payload/*.app/Info.plist)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Autoloader v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            upload/Autoloader.ipa
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
